language: minimal

before_deploy:
    - echo $TRAVIS_TAG > .version
    - zip -q -r $TRAVIS_TAG.zip ./def/* .version

deploy:
    provider: releases
    api_key: "$GITHUB_TOKEN"
    file: "$TRAVIS_TAG.zip"
    skip_cleanup: true
    on:
        tags: true
