
name: Package

on:
  push:
    tags: "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Zip
        run: |
          echo ${{ github.ref }} > .version
          zip -q -r ${{ github.ref }}.zip ./def/* .version

      - name: Upload Assets
        uses: softprops/action-gh-release@v0.1.7
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          body: ${{ github.ref }}
          files: |
            *.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
